### ISSUE TITLE
Cloudant credential information should specify protocol is required

### ISSUE THREAD

**Issue by osowski** [ibm-cloud-architecture/refarch-cloudnative-micro-socialreview#19]
The Cloudant configuration credentials are currently organized like
```
cloudant:
    username: {your_cloudant_username}
    password: {your_cloudant_password}
    host: {your_cloudant_host}
```

However, the Bluemix credentials are formatted like
```
{
  "username": "zzzzzzz-ea64-4b74-859c-yyyyyyyyy-bluemix",
  "password": "9361asdfaaaaaaaaaa85fb48b77f92ae69dfb3c4731a57b98a266cffb9",
  "host": "aaaaaaaaaaaa-859c-0ca5b00b0d54-bluemix.cloudant.com",
  "port": 443,
  "url": "https://zzzzzzz-ea64-4b74-859c-yyyyyyyyy-bluemix:9361asdfaaaaaaaaaa85fb48b77f92ae69dfb3c4731a57b98a266cffb9@aaaaaaaaaaaa-859c-0ca5b00b0d54-bluemix.cloudant.com"
}
```

The protocol from the Bluemix Couldant `URL` property is required for the `host` property of the app.  In the above examples `cloudant.host` should equal `https://aaaaaaaaaaaa-859c-0ca5b00b0d54-bluemix.cloudant.com`.
